---
# vars file for install_ssh_pam_ldap
__ldap_nslcd_uid: nslcd
__ldap_nslcd_gid: nslcd
--ldap_server_uri: ldap://ldap.casd.local/
__ldap_server_base_dn: dc=casd,dc=local
__ldap_debconf_utils_package: debconf-utils
__ldap_ca_certs: /etc/ssl/certs/ca-certificates.crt
__ldap_client_pkgs:
  - libnss-ldapd
  - libpam-ldapd