---

- name: Download Jetty 9
  get_url:
#    url: http://download.eclipse.org/jetty/stable-9/dist/jetty-distribution-{{ jetty_version }}.tar.gz
    url: http://eclipse.org/downloads/download.php?file=/jetty/9.3.2.v20150730/dist/jetty-distribution-9.3.2.v20150730.zip&r=1
    dest: /opt/jetty-distribution-{{ jetty_version }}.tar.gz
    sha256sum: ad3086ca320843c99eb9e3dfc5aec784be44fb1339993e708112f871dc46248f
    force: no

- name: Extract Jetty 9
  unarchive:
    src: /opt/jetty-distribution-{{ jetty_version }}.tar.gz
    dest: /opt/
    copy: no
    owner: jetty
    group: jetty

